### PR TITLE
High visibility icons

### PR DESCRIPTION
**Pull request by Reenuip**
I made edits of the original muted/unmuted status icons for better visibility. The microphone is larger and is striked out with a thick red line when muted.

### CODE REVIEW

**Comment by SaifAqqad** [comment]
Thank you for the PR, the icon looks great.

Although I think it should have a thin dark outline so it's more visible on white backgrounds, as you can see in the screenshot below it's barely visible
image

**Comment by Reenuip** [comment]
Sure, I could definitely give the whole thing an outline, but it might not look great in the system tray at 16x16px unless I make a pixel-perfect version. If that turns out to be necessary, you may want to consider using different resources for the OSD microphone icon and the system tray.
I was under the impression that the dark icons in the Resources folder were used in certain configurations, but I haven't found where they're used. Maybe we could expose some toggle in the UI between the light and dark icons.
Either way, I'll soon get around to making some changes to the base icons and play with different scales.

**Comment by SaifAqqad** [comment]
Yeah, I think I'll need to use separate icons for the overlay, also might as well add the option to choose between light and dark in that case.

currently, the black icon is only used for the tray and only when windows 10/11 is set to light mode.

**Comment by Reenuip** [comment]
Sounds good. I already made a vector version of the base microphone, so I can crank out the different sizes in a bit. What is the size of the overlay version? Been searching through the scripts, but I can't find the spec.

**Comment by Reenuip** [comment]
Sounds good, Saif. I'll get working on those later tonight. Thanks for the info!

**Comment by SaifAqqad** [comment]
Thank you, the icons look great, I will merge this now.

I'm gonna work on the overlay though, I'm looking into using [Gdip](https://github.com/tariqporter/Gdip/blob/master/Gdip.ahk) to render the icon because it looks really awful right now 
image

**Comment by roughnecks** [comment]
yeah, overlay is all grainy/blurred, looks low res or something.

**Comment by SaifAqqad** [comment]
I can confirm Gdip does indeed fix the issue 
image image

**Comment by Reenuip** [comment]
> I can confirm Gdip does indeed fix the issue

Cool. I was about to experiment with a transparent background to see if that helps, but this is looking very nice.

**Comment by SaifAqqad** [comment]
@Reenuip sorry for the delay (I was busy with other stuff).
I have pushed the new overlay, you can test it out in the [pre-release](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit) version if you want, I still need to add the new overlay options to the config UI though

**Pull request merged**
